# version: "3.9"

# services:
#   node:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: daisyEtm
#     restart: unless-stopped
#     tty: true
#     working_dir: /var/www/app
#     ports:
#       - "80:80"
#     volumes:
#       - ./:/var/www/app
#     depends_on:
#       - mongo

#   mongo:
#     image: mongo:latest
#     restart: unless-stopped
#     ports:
#       - "27017:27017"

#   mongo-express:
#     image: mongo-express
#     restart: always
#     ports:
#       - "8081:8081"
#     environment:
#       ME_CONFIG_MONGODB_SERVER: "mongo"
#       ME_CONFIG_BASICAUTH_USERNAME: "admin"
#       ME_CONFIG_BASICAUTH_PASSWORD: "password"

# volumes:
#   mongo-data:
